### ISSUE TITLE
Unable to launch module configuration

### ISSUE THREAD

**Issue by Molkobain** [VonOx/gladys-onkyo#4]
**Describe the bug**
Exception thrown when launching module configuration from Gladys backend.

**To Reproduce**
1. Go to _Gladys backend > Modules menu_
2. Click on _Configuration_ on the module's row
3. Nothing happens in the backend but there is the error below showing up in the logs
4. No device is shown in the _Devices_ menu (I'm able to access it through the Onkyo Android app)

```
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/opt/gladys/api/hooks/onkyo/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/opt/gladys/api/hooks/onkyo/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Informations:**
 - OS: Raspbian 8 (Jessie)
 - Gladys version: 3.10.3
 - Node version: 10.12.0
 - Module version: 1.1.1
 - Onkyo Model: TX-NR515

**Comment by VonOx** [comment]
I have some timeout also with my onkyo avr. I need to completly shutdown and power on. (remove plug)

**Comment by Molkobain** [comment]
I tried that but got no luck 😕
Maybe the receiver is too old and not compatible.

**Comment by VonOx** [comment]
No it's OK your model is compatible.

Can you test the python version?

https://github.com/miracle2k/onkyo-eiscp

**Comment by Molkobain** [comment]
The python version works, I tried the following commands:

```
$ onkyo --discover
TX-NR515        192.168.xx.yy:zzzz     0009B0CAxyz
$ onkyo -i 0009B0CAxyz volume=2
TX-NR515: master-volume = 2
$ onkyo -i 0009B0CAxyz volume=20
TX-NR515: master-volume = 20
$ onkyo -i 0009B0CAxyz volume=15
TX-NR515: master-volume = 15
```

That being said, it takes arount 5s to execute which seems to be quite long no?

**Comment by VonOx** [comment]
@Molkobain  good catch , 5s is to mutch.

I have no idea on how to solve this...

**Comment by VonOx** [comment]
Can you test on other Platform ( not rpi ) ?

**Comment by Molkobain** [comment]
Do you mean your module through another Gladys device or the python lib? I'm gonna set up an Ubuntu VM :)

**Comment by VonOx** [comment]
No just the python lib is ok

**Comment by Molkobain** [comment]
Tested on 2 Ubuntu VMs (17.04 & 18.04), the python lib takes less than 1 second when a give both the _--host_ and _--port_ parameters. Around 3-4 seconds when I just give _--id_ parameter.

On the RPi with _--host_ and _--port_ it takes around 3-4s. Yesterday I was giving only the _--id_ parameter when I measured 5s.

**Comment by Molkobain** [comment]
What command do you send to the receiver? I saw in the package.json that there is a dependancy to the onkyo.js package, but I didn't found it in npm.

**Comment by VonOx** [comment]
Weird because it is available

Sources are here https://github.com/jupe/onkyo.js

I use a discover function

**Comment by Molkobain** [comment]
From what I see in the lib, using the discover function takes some time as it broadcasts to the whole network and waits for answers.

I tried to modify your lib/onkyo.setup.js to make it use the _Onkyo_ object instead of the _OnkyoDiscover_ with the following code:

```
const {Onkyo} = require('onkyo.js');
const onkyo = Onkyo({address: '192.168.xx.yy'});
sails.log.debug(onkyo);
```

And I got results!

```
Onkyo {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  logger:
   { debug:
      { [Function: debug]
        namespace: 'onkyo.js',
        enabled: false,
        useColors: true,
        color: 2,
        destroy: [Function: destroy],
        extend: [Function: extend],
        inspectOpts: {} },
     ...,
  device:
   { name: 'onkyo',
     address: '192.168.xx.yy',
     port: 60128,
     info: undefined },
  _client: null,
  _buffer: <Buffer >,
  deviceState: {},
  powerOn: [Function: f],
  powerOff: [Function: f],
  powerStatus: [Function: f],
  ...
```

So the lib is working with this receiver, just a timeout issue maybe. I'll check into onkyo.js to see if the timeout comes from it or my nodejs server.

_Note: As you can see, the onkyo.device.info is undefined so I to manually populate it in order for your setup script to complete._

**Comment by VonOx** [comment]
If you create device and devicetype manually in Gladys the setup is useless.

The timeout come from bluebird promise.
I want to handle this behavior and document manual setup. 

And thank you for feedback :blush:

**Comment by Molkobain** [comment]
Maybe [this](https://github.com/jupe/onkyo.js/blob/master/lib/OnkyoDiscover.js#L127) is a lead. Do you where dependancies are stored? I could try to hack the timeout part to see if it solves the problem.

**Comment by Molkobain** [comment]
> If you create device and devicetype manually in Gladys the setup is useless.

Yeah obviously, I wanted to run it like this to be sure what the issue was (and create the deviceTypes in the process)

**Comment by VonOx** [comment]
It's stored in node_module folder
